apiVersion: fleet.cattle.io/v1alpha1
kind: ClusterGroup
metadata:
  name: country-es
  namespace: fleet-default
spec:
  selector:
    matchExpressions: []
    matchLabels:
      sisalcloud.it/country: es
