apiVersion: fleet.cattle.io/v1alpha1
kind: ClusterGroup
metadata:
  name: dc-of
  namespace: fleet-default
spec:
  selector:
    matchExpressions: []
    matchLabels:
      sisalcloud.it/datacenter: of
